{
  "comments": [
    {
      "unresolved": true,
      "key": {
        "uuid": "f2913294_42095649",
        "filename": "tools/bump.py",
        "patchSetId": 2
      },
      "lineNbr": 48,
      "author": {
        "id": 1120458
      },
      "writtenOn": "2024-02-06T20:55:21Z",
      "side": 1,
      "message": "error in this case, because it\u0027s unexpected to be running the script with these arguments?",
      "range": {
        "startLine": 48,
        "startChar": 0,
        "endLine": 48,
        "endChar": 75
      },
      "revId": "81b64d3de9d0198d5a71aeca7943f242e1e9f5cc",
      "serverId": "85c56323-6fa9-3386-8a01-6480fb634889"
    }
  ]
}